version: '3'
services:
  node-app:
    image: node:latest
    container_name: node-app-container
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run build
        node -r dotenv/config build